---
apiVersion: wego.weave.works/v1alpha1
kind: Application
metadata:
  labels:
    wego.weave.works/app-identifier: wego-5c282d63334aa8bbdc942a4b4544e031
  name: microservices-demo
  namespace: wego-system
spec:
  branch: master
  config_url: ssh://git@github.com/sympatheticmoose/tmp-gitops.git
  deployment_type: kustomize
  path: ./deploy/kubernetes/helm-chart
  source_type: git
  url: ssh://git@github.com/sympatheticmoose/microservices-demo.git
